import Footer from '@/components/footer/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { Open_Sans } from 'next/font/google'
const openSans = Open_Sans({ subsets: ['latin']})
import Navbar from '@/components/navbar/Navbar'
import NextTopLoader from "nextjs-toploader";
import ReduxStoreProvider from '@/redux/provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <ReduxStoreProvider>
          <NextTopLoader
            color="#ff9800"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #ff9800,0 0 5px #ff9800"
          />
          <Navbar />
          {children}
          <Footer />
        </ReduxStoreProvider>
      </body>
    </html>
  )
}